export { default as ProductPage} from './ProductPage'
export { default as Header} from './Header'
export { default as Footer} from './Footer'
export { default as ProductSpecs} from './ProductSpecs'
export { default as ProductButton} from './ProductButton'
export { default as ProductImage} from './ProductImage'
export { default as Test} from './Test'
